### 点积

向量 ${\displaystyle {\vec {a}}=[a_{1},a_{2},\cdots ,a_{n}]}$ 和 ${\displaystyle {\vec {b}}=[b_{1},b_{2},\cdots ,b_{n}]}$ 的点积定义为：

${\displaystyle {\vec {a}}\cdot {\vec {b}}=\sum _{i=1}^{n}a_{i}b_{i}=a_{1}b_{1}+a_{2}b_{2}+\cdots +a_{n}b_{n}}$

- $\Sigma$ 是求和符号
- $n$ 是向量空间的维数

例如，两个三维向量${\displaystyle \left[1,3,-5\right]}$和${\displaystyle \left[4,-2,-1\right]}$的点积是

$$
{\displaystyle {\begin{aligned}\ [1,3,-5]\cdot [4,-2,-1]&=(1)(4)+(3)(-2)+(-5)(-1)\\&=4-6+5\\&=3\end{aligned}}}
$$

In [1]:
import torch

A = torch.tensor([1, 3, -5])
B = torch.tensor([4, -2, -1])

print(torch.dot(A, B))

tensor(3)


### 加减法

当这两个向量数值、方向都不同，基本向量$\vec{e}_1=(1,0,0),\vec{e}_2=(0,1,0),\vec{e}_3=(0,0,1)$时，向量和计算为 ${\displaystyle {\vec {a}}+{\vec {b}}=(a_{1}+b_{1}){\vec {e}}_{1}+(a_{2}+b_{2}){\vec {e}}_{2}+(a_{3}+b_{3}){\vec {e}}_{3}}$

In [2]:
print(A+B)
print(A-B)

tensor([ 5,  1, -6])
tensor([-3,  5, -4])


### 范数

已知向量的坐标，就可以知道它的模长。设向量${\displaystyle {\vec {v}}=(v_{1},v_{2},\cdots ,v_{n})}$，其范数的计算表达式由弗罗贝尼乌斯范数（一种同时适用于向量和矩阵的范数计算方法）给出：${\displaystyle \left\|{\vec {v}}\right\|={\sqrt {v_{1}^{2}+v_{2}^{2}+\cdots +v_{n}^{2}}}}$。

简单说，范数是点到坐标零点的距离

In [4]:
a = torch.arange(9, dtype=torch.float) - 4
b = a.reshape((3, 3))
print(a,b)
# 16+9+4+1+0+1+4+9+16 = 60 根号60=7.746
print(torch.norm(a),torch.norm(b))
# 计算 a 和 b 的正无穷范数（所有元素中绝对值最大的）
# 正无穷范数：所有元素中绝对值最大的
print(torch.norm(a, float('inf')),torch.norm(b, float('inf')))

tensor([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.]) tensor([[-4., -3., -2.],
        [-1.,  0.,  1.],
        [ 2.,  3.,  4.]])
tensor(7.7460) tensor(7.7460)
tensor(4.) tensor(4.)


In [5]:
c = torch.tensor([[1, 2, 3], [-1, 1, 4]], dtype=torch.float)
print(c)
# 沿着第 0 维（列）、第 1 维（行）的范数。默认情况下，torch.norm 计算的是二范数（欧几里得范数），即每列元素平方和的平方根
# sqrt(1^2+(-1)^2) = sqrt(2) = 1.41
# sqrt(1^2+2^2+3^2) = sqrt(14) = 3.74
print(torch.norm(c, dim=0), torch.norm(c, dim=1))
# 沿着第 1 维（行）的 L1 范数，即每行元素绝对值的和 L1 范数：|1.0| + |2.0| + |3.0| = 1 + 2 + 3 = 6
print(torch.norm(c, p=1, dim=1))

tensor([[ 1.,  2.,  3.],
        [-1.,  1.,  4.]])
tensor([1.4142, 2.2361, 5.0000]) tensor([3.7417, 4.2426]) tensor([6., 6.])


In [6]:
d = torch.arange(8, dtype=torch.float).reshape(2, 2, 2)
print(d)

# 沿着第 1 和第 2 维的范数。默认情况下，torch.norm 计算的是二范数（欧几里得范数），即每个切片的元素平方和的平方根。
# 第一个切片 d[0, :, :]：元素：[0., 1., 2., 3.]
# 二范数：sqrt(0^2 + 1^2 + 2^2 + 3^2) = sqrt(0 + 1 + 4 + 9) = sqrt(14) ≈ 3.742
# 第二个切片 d[1, :, :]：元素：[4., 5., 6., 7.]
# 二范数：sqrt(4^2 + 5^2 + 6^2 + 7^2) = sqrt(16 + 25 + 36 + 49) = sqrt(126) ≈ 11.225
print(torch.norm(d, dim=(1, 2)))

# 第一个切片 d[0, :, :] 的范数。这个切片是一个 2x2 的张量，默认情况下计算的是二范数。
# 元素：[0., 1., 2., 3.]
# 二范数：sqrt(0^2 + 1^2 + 2^2 + 3^2) = sqrt(0 + 1 + 4 + 9) = sqrt(14) ≈ 3.742
print(torch.norm(d[0, :, :]))

# 第二个切片 d[1, :, :] 的范数。这个切片也是一个 2x2 的张量，默认情况下计算的是二范数。
# 元素：[4., 5., 6., 7.]
# 二范数：sqrt(4^2 + 5^2 + 6^2 + 7^2) = sqrt(16 + 25 + 36 + 49) = sqrt(126) ≈ 11.225
print(torch.norm(d[1, :, :]))

tensor([[[0., 1.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.]]])
tensor([ 3.7417, 11.2250])
tensor(3.7417)
tensor(11.2250)
